// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingPlatform.Api.Infrastructure.Persistence;

#nullable disable

namespace TradingPlatform.Api.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260827150445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingPlatform.Api.Domain.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("TradeId");

                    b.HasIndex("Symbol");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trades_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Trades_Side", "[Side] IN ('Buy', 'Sell')");

                            t.HasCheckConstraint("CK_Trades_Status", "[Status] IN ('Filled', 'Rejected')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
